name: Code Quality

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check code formatting
      run: |
        # Check if there are any TypeScript files that need formatting
        echo "Checking TypeScript code style..."

        # Basic style checks
        echo "Checking for console.log statements..."
        if grep -r "console\.log" src/ --include="*.ts" --exclude-dir=node_modules; then
          echo "Warning: Found console.log statements in source code"
        fi

        echo "Checking for TODO comments..."
        if grep -r "TODO\|FIXME\|HACK" src/ --include="*.ts" --exclude-dir=node_modules; then
          echo "Info: Found TODO/FIXME/HACK comments"
        fi

    - name: Check dependencies
      run: |
        echo "Checking for security vulnerabilities..."
        npm audit --audit-level=moderate

        echo "Checking for outdated dependencies..."
        npm outdated || true

    - name: Validate TypeScript configuration
      run: |
        echo "Validating tsconfig.json..."
        npx tsc --noEmit --skipLibCheck

        if [ ! -f "tsconfig.json" ]; then
          echo "Error: tsconfig.json not found"
          exit 1
        fi

    - name: Check bundle size
      run: |
        npm run build

        if [ -f "main.js" ]; then
          size=$(stat -c%s main.js 2>/dev/null || stat -f%z main.js)
          size_mb=$((size / 1024 / 1024))

          echo "Bundle size: ${size} bytes (${size_mb}MB)"

          if [ $size -gt 2097152 ]; then  # 2MB
            echo "Warning: Bundle size is quite large (>2MB)"
          fi
        fi

  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: |
        echo "Running npm security audit..."
        npm audit --audit-level=high

    - name: Check for sensitive data
      run: |
        echo "Checking for potential sensitive data..."

        # Check for common patterns that might indicate sensitive data
        patterns=("password" "secret" "token" "key" "api_key" "private")

        for pattern in "${patterns[@]}"; do
          echo "Checking for pattern: $pattern"
          if grep -ri "$pattern" src/ --include="*.ts" --exclude-dir=node_modules | grep -v "// " | grep -v "interface\|type\|class"; then
            echo "Warning: Found potential sensitive data pattern: $pattern"
          fi
        done